In [26]:
import numpy as np

In [27]:
# 1.1.3

mat_a = np.matrix('1 1 1; 0 1 1; 0 0 1')
mat_b = np.matrix('7 5 3; 0 7 5; 0 0 7')

print('AB:\n', mat_a * mat_b)
print('BA:\n', mat_b * mat_a)

print('AB - BA:')
print(mat_a * mat_b - mat_b * mat_a)

AB:
 [[ 7 12 15]
 [ 0  7 12]
 [ 0  0  7]]
BA:
 [[ 7 12 15]
 [ 0  7 12]
 [ 0  0  7]]
AB - BA:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [28]:
# 1.2.3
mat_a = [['a', 0, 0, 0], [0, 'b', 0, 0], [0, 0, 'c', 0], [0, 0, 0, 'd']]

mat_c = [[] for i in range(len(mat_a))]

for i in range(4):
    for j in range(4):
        if mat_a[i][j] == mat_a[j][i] and mat_a[i][j] != 0:
            mat_c[i].append('2'+mat_a[i][j])
        elif mat_a[i][j] != mat_a[j][i] and mat_a[i][j] != 0 and mat_a[j][i] != 0:
            mat_c[i].append(mat_a[i][j]+mat_a[j][i])
        else:
            mat_c[i].append(mat_a[i][j]*mat_a[j][i])

print('A^2:')
for row in mat_c:
    print(row)

A^2:
['2a', 0, 0, 0]
[0, '2b', 0, 0]
[0, 0, '2c', 0]
[0, 0, 0, '2d']


In [29]:
# 1.3.4
mat_a = np.matrix('5 0 2 3; 4 1 5 3; 3 1 -1 2')
mat_b = np.matrix('6 -2 7 4')

try:
    mat_c = mat_a * mat_b
    print('AB =')
    print(mat_c)
except ValueError as e:
    print('AB cannot be calculated')
    print(e)

AB cannot be calculated
shapes (3,4) and (1,4) not aligned: 4 (dim 1) != 1 (dim 0)


In [30]:
# 1.4.4
mat_a = np.matrix('1 2 3; -1 2 1; 1 3 2')
mat_a_det = np.linalg.det(mat_a)

print(f'|A|: {mat_a_det:.2g}')

|A|: -8


In [31]:
# 1.5.3
mat_a = np.matrix('1 2 0 0 0; 1 0 2 0 0; 1 0 0 2 0; 1 0 0 0 2; 0 0 1 1 1')
mat_a_det = np.linalg.det(mat_a)

print(f'|A|: {mat_a_det:.2g}')

|A|: -24


In [32]:
# 1.6.4
mat_a = np.matrix('2 1 0 0; 3 2 0 0; 1 1 3 4; 2 -1 2 3')
mat_a_inv = np.linalg.inv(mat_a)

print('A^-1:')
print(mat_a_inv)

A^-1:
[[  2.  -1.   0.   0.]
 [ -3.   2.  -0.  -0.]
 [ 31. -19.   3.  -4.]
 [-23.  14.  -2.   3.]]


In [33]:
# 1.7.3
mat_a = np.matrix('-2 3 1 -1; 3 2 1 4; 1 2 3 4; 0 2 3 3')
mat_a_rank = np.linalg.matrix_rank(mat_a)

print(f'rank(A): {mat_a_rank}')

rank(A): 3


In [34]:
# 1.8.24
def kramer(A, B):
    A_det = np.linalg.det(A)
    
    # Check if |A| = 0
    if not A_det:
        raise ValueError('Determinant of A is zero')
    
    # x matrix
    x_mat = np.matrix(A)
    x_mat[:, 0] = B

    # y matrix
    y_mat = np.matrix(A)
    y_mat[:, 1] = B

    # z matrix
    z_mat = np.matrix(A)
    z_mat[:, 2] = B

    x = np.linalg.det(x_mat) / A_det
    y = np.linalg.det(y_mat) / A_det
    z = np.linalg.det(z_mat) / A_det

    return x, y, z

mat_a = np.matrix('1 2 -1; 3 4 1; 5 1 -3')
mat_b = np.matrix('-3; 1; -2')

x, y, z = kramer(mat_a, mat_b)
print(f'x: {x: .2f}\ny: {y: .2f}\nz: {z: .2f}')

x:  1.00
y: -1.00
z:  2.00


In [35]:
# 2.6
import random

# Get size of matrix
n = int(input('Enter n: ')); m = int(input('Enter m: '))

# Generate random matrix
mat_a = np.matrix([[random.randint(-10, 10) for j in range(m)] for i in range(n)])

# Generate list amounts of negative numbers in each row
row_neg = [sum([1 for j in range(m) if mat_a[i, j] < 0]) for i in range(n)]
# Generate list amounts of negative numbers in each column
col_neg = [sum([1 for i in range(n) if mat_a[i, j] < 0]) for j in range(m)]

# Print matrix with negative amounts by rows and columns
print('Matrix:')
for i in col_neg:
    print(f' ({i})', end='')

print()

for i in range(n):
    for j in range(m):
        print(f'{mat_a[i, j]: 3d}', end=' ')
    print(f'({row_neg[i]})')

Matrix:
 (3) (2) (2) (6) (3) (5) (4) (2)
  0   2   5   5  -3   6  -1   6 (2)
  5   0   6  -1   2   7   5   9 (1)
  8   9   0  -4   4   6  -4   9 (2)
  0   2   8  -5   1 -10  -1  -1 (4)
  6 -10  -3  -7  -1  -4 -10   3 (6)
 -8   0  -9 -10   7  -7  10   4 (4)
 -2  10   1   9   6  -9   2   3 (2)
 -2  -2   4  -7  -4  -2   4  -7 (6)
